[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[profile.sepolia]
inherits = "default"
rpc_url = "${ALCHEMY_SEPOLIA_URL}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[profile.local]
inherits = "default"
rpc_url = "http://127.0.0.1:8545"
chain_id = 31337


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
